### ISSUE TITLE
Machine  mode atomic extension tests?

### ISSUE THREAD

**Issue by aprnath** [riscv/riscv-compliance#47]
The Atomic suite in this repository is labeled 'ua'. Are there any machine mode only Atomic extension compliance suite tests?

**Comment by allenjbaum** [comment]
Other will correct me, for sure, but:
The only difference in a machine mode vs. user mode test for this is
whether this is executed in VM mode with address translation (with the
implication it could trap).
Since this test is in the unprivileged test suite, it shouldn't require
privileged resources (and, indeed, the tests themselves don't),  and
shouldn't cause traps (which require privileged mode resources).
So this may be in user mode test, but it should (or could) be operating in
a bare physical-only mode or under VM and either in Mmode or uMode.
Having said that: I would expect similar tests in the privileged test suite
that would add test that get page faults, etc.

**Comment by neelgala** [comment]
The ua tests will be deprecated for now. They were directly borrowed from the riscv-tests repo for reference purposes. Dedicated tests for the A extension (machine, supervisor, user) are yet to be developed by the compliance group.
